const express = require('express')
const app = express()
const midiW = require('./midi/midi-wrapper')
const sseRoute = require('./routes/sse/sse.js')
const driversRoute = require('./routes/drivers/drivers.js')
const socketRoute = require('./routes/socket/socket.io.js')
const { initMidi } = require('./midi/initMidi')

const init = require('./server/init.js')

driversRoute(app, midiW)
socketRoute(app)
const { output, input } = initMidi(midiW)
init(app, { output })
sseRoute(app, { output, input })
