const express = require('express')
const app = express()
const midi = require('./midi/midi-wrapper')
const sseRoute = require('./routes/sse/sse.js')
const driversRoute = require('./routes/drivers/drivers.js')
const socketRoute = require('./routes/socket/socket.io.js')
const { initMidi } = require('./midi/initMidi')
const init = require('./server/init.js')
const logMiddleware = require('./middleware/logMiddleware')

app.use(logMiddleware)
logMiddleware.logger.info('Starting Service ....')
socketRoute(app)
const { output, input } = initMidi(midi)
driversRoute(app, midi, { output, input })

init(app, { output })
sseRoute(app, { output, input })
